-- DM 排班域初始化脚本（PostgreSQL）
-- 后端 DataInitializer 也会以兼容 H2/PostgreSQL 的方式执行建表与种子数据，
-- 本脚本保证数据库容器首次启动时结构就绪。

CREATE TABLE IF NOT EXISTS dm (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  skills VARCHAR(400) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS dm_shift (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_date DATE NOT NULL,
  start_time VARCHAR(5) NOT NULL,
  required_skill VARCHAR(40) NOT NULL,
  required_count INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_dm_shift_slot_skill UNIQUE (work_date, start_time, required_skill)
);

CREATE TABLE IF NOT EXISTS shift_assignment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_id BIGINT NOT NULL,
  dm_id BIGINT NOT NULL,
  work_date DATE NOT NULL,
  start_time VARCHAR(5) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_assignment_dm_slot UNIQUE (dm_id, work_date, start_time)
);

CREATE TABLE IF NOT EXISTS swap_request (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_shift_id BIGINT NOT NULL,
  from_work_date DATE NOT NULL,
  from_start_time VARCHAR(5) NOT NULL,
  required_skill VARCHAR(40) NOT NULL,
  to_shift_id BIGINT,
  to_work_date DATE,
  to_start_time VARCHAR(5),
  requester_id BIGINT NOT NULL,
  target_id BIGINT NOT NULL,
  status VARCHAR(12) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_shift_date ON dm_shift (work_date);
CREATE INDEX IF NOT EXISTS idx_assignment_shift ON shift_assignment (shift_id);
CREATE INDEX IF NOT EXISTS idx_swap_target_status ON swap_request (target_id, status);

CREATE TABLE IF NOT EXISTS operation_records (
  id SERIAL PRIMARY KEY,
  module_name VARCHAR(120) NOT NULL,
  owner_name VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL,
  metric VARCHAR(40) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
